version: "3.9"

services:
  sql-fcg-payments:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-fcg-payments
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NovaSenhaForte123!"
      MSSQL_PID: "Developer"
    ports:
      - "14333:1433"
    volumes:
      - sql-fcg-payments_data:/var/opt/mssql

  sql-tools-fcg-games:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql-tools-fcg-payments
    depends_on:
      - sql-fcg-payments
    entrypoint: /bin/bash
    command: >
      -c "
      echo 'Aguardando SQL Server...';
      until /opt/mssql-tools/bin/sqlcmd -S sql-fcg-payments -U sa -P 'NovaSenhaForte123!' -Q 'SELECT 1' &> /dev/null; do
        sleep 2;
      done;
      echo 'SQL Server pronto. Criando banco se n√£o existir...';
      /opt/mssql-tools/bin/sqlcmd -S sql-fcg-payments -U sa -P 'NovaSenhaForte123!' -Q \"IF DB_ID('fcg-payments') IS NULL CREATE DATABASE [fcg-payments]\"
      "

volumes:
  sql-fcg-payments_data:
